name: Inputs Demo
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: Choose the environment to deply
        required: true
        default: dev
        type: choice
        options:
          - dev
          - test
          - prod
      tag:
        description: Choose the git tag to deploy
        required: true
jobs:
     inputs-demo:
       runs-on: ubuntu-latest
       steps:
        - name: Deploy the App
          run: echo "Deploying the ${{ inputs.artifact_tag }} application to ${{ inputs.environment }}"
        
